POST http://localhost:88/api/product/category/delete
Content-Type: application/json

[1422]

###
GET localhost:10001/product/category/list/tree

###

POST localhost:10001/product/category/delete
Content-Type: application/json

###

POST http://localhost:88/api/product/brand/update
Content-Type: application/json

{"brandId":1,"showStatus":4}

###

POST http://localhost:88/api/product/brand/save
Content-Type: application/json

{"name": "22","brandId": 3}

###

POST http://localhost:88/api/ware/purchase/received
Content-Type: application/json

[8]

###

POST http://localhost:88/api/ware/purchase/done
Content-Type: application/json

{
  "id":8,
  "items":[
    {"itemId": 6,"status": 3,"reason": ""}
  ]
}