server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://192.168.248.128:3306/gulimall_oms?characterEncoding=UTF-8
    username: root
    password: xw19980412
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto