spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000
alibaba:
  cloud:
    access-key: LTAI5tBFFsTiXgessjJFvPN6
    secret-key: UZxj0pn6OBOn6C7AZvt6awtyIDztsQ
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimall-test-zqc